import { Inter } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Coffee shop",
  description: "Generated by create next app",
};

const comicFont = localFont({
  src: 'comic.ttf'
})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={comicFont.className}>{children}</body>
    </html>
  );
}
